import React from "react";
import "../styles/global.css";
import "../styles/theme.css";
import { Ropa_Sans } from "next/font/google";

const ropaSans = Ropa_Sans({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "하효니 작업중",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body>{children}</body>
    </html>
  );
}
